title: "Blog-vjezba"

# Netlify domena
url: "https://blog-vjezba.netlify.app"

# Na Netlifyju MORA biti prazno
baseurl: ""

collections:
  vjencanja:
    output: true # << OVO je ključno da se generiraju stranice
    permalink: "/vjencanja/:name/" # /vjencanja/IME-FILEA/

# (nije obavezno, ali jako korisno: default layout za vjenčanja)
defaults:
  - scope:
      path: "_vjencanja"
      type: "vjencanja"
    values:
      layout: "vjencanje"
