title: "Blog-vjezba"

# Netlify domena:
url: "https://blog-vjezba.netlify.app"

# NA NETLIFYJU MORA BITI PRAZNO:
baseurl: ""

collections:
  vjencanja:
    output: true
    permalink: "/vjencanja/:name/"
