backend:
  name: git-gateway
  branch: main

media_folder: "assets/img/uploads"
public_folder: "/assets/img/uploads"

collections:
  - name: "vjencanja"
    label: "Vjenčanja"
    folder: "_vjencanja"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Naslov", name: "title", widget: "string" }
      - { label: "Datum", name: "date", widget: "datetime" }
      - { label: "Cover slika", name: "cover_image", widget: "image" }
      - {
          label: "Imena para",
          name: "couple",
          widget: "string",
          required: false,
        }
      - {
          label: "Lokacija",
          name: "location",
          widget: "string",
          required: false,
        }
      - {
          label: "Kratki opis",
          name: "excerpt",
          widget: "text",
          required: false,
        }
      - { label: "Tekst", name: "body", widget: "markdown" }
      - label: "Galerija"
        name: "gallery"
        widget: "list"
        required: false
        hint: "Dodaj više fotografija za galeriju"
        fields:
          - { label: "Fotografija", name: "image", widget: "image" }
          - {
              label: "Alt tekst",
              name: "alt",
              widget: "string",
              required: false,
            }

  - name: "rucni_rad" # naziv kolekcije
    label: "Ručni rad" # što CMS prikazuje
    folder: "_rucni_rad" # gdje se spremaju .md fajlovi
    create: true # možeš dodavati nove
    slug: "{{slug}}" # adresa proizvoda
    fields:
      - { name: "title", label: "Naziv proizvoda", widget: "string" }
      - { name: "price", label: "Cijena", widget: "string", required: false }
      - { name: "cover_image", label: "Glavna slika", widget: "image" }
      - label: "Galerija"
        name: "gallery"
        widget: "list"
        field: { label: "Slika", name: "image", widget: "image" }
      - { name: "body", label: "Opis proizvoda", widget: "markdown" }
      - { name: "layout", widget: "hidden", default: "proizvodi" }
      - {
          name: "materials",
          label: "Materijali",
          widget: "list",
          required: false,
        }
      - {
          name: "dimensions",
          label: "Dimenzije",
          widget: "string",
          required: false,
        }
      - {
          name: "availability",
          label: "Dostupnost",
          widget: "string",
          required: false,
        }
